ARG DISTROLESS_TAG="latest"

FROM container-registry.oracle.com/graalvm/native-image:24 AS build

ARG PROJECT_NAME

WORKDIR /
COPY "./bundle.nib" bundle.nib

RUN native-image -o "./app" --bundle-apply="bundle.nib"
COPY nvtop .

FROM gcr.io/distroless/cc:${DISTROLESS_TAG}

WORKDIR /

COPY --from=build --chown=root:root /bundle.output/default/app ./app
COPY --from=build /nvtop .

ENV FFWD_ARCHITECTURE=aarch64

USER root
ENTRYPOINT ["./app"]
