ARG DISTROLESS_TAG="latest"

FROM container-registry.oracle.com/graalvm/native-image:25 AS build

ARG PROJECT_NAME

WORKDIR /
COPY "./bundle.nib" bundle.nib
COPY nvtop .
COPY gnmic .

RUN native-image -o "./app" \
    --bundle-apply="bundle.nib" \
    --enable-native-access=ALL-UNNAMED

FROM ubuntu:24.04 AS deps

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update
RUN apt-get install -y \
    libncurses5-dev libncursesw5-dev libdrm-dev libsystemd-dev libdrm-amdgpu1 software-properties-common
RUN add-apt-repository -y ppa:vbernat/haproxy-3.2
RUN apt-get install -y haproxy=3.2.\*

FROM gcr.io/distroless/cc:${DISTROLESS_TAG}

WORKDIR /

ENV FFWD_ARCHITECTURE=aarch64

COPY --from=deps /lib/${FFWD_ARCHITECTURE}-linux-gnu /lib/${FFWD_ARCHITECTURE}-linux-gnu

COPY --from=build --chown=root:root /bundle.output/default/app ./app
COPY --from=build /nvtop .
COPY --from=build /gnmic .
COPY --from=deps /usr/sbin/haproxy .

USER root
ENTRYPOINT ["./app"]
