name: build-graalvm-images
run-name: Build ${{ inputs.project_name }} GraalVM image (${{ inputs.version }})

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: Origin project name
        required: true
      version:
        description: The version of the image to be built
        required: true
      bundle_s3_uri:
        description: The S3 URI (s3://{bucket}/{object_key}) for the GraalVM bundle
        required: true
      is_latest:
        description: If the images should be tagged as 'latest'
        type: boolean
        required: true
      is_testing:
        description: If the images should be tagged as 'testing'
        type: boolean
        required: true
      tag:
        description: Additional tag for the image, if any

env:
  PUBLIC_REGISTRY: ghcr.io
  REPOSITORY: core0

jobs:
  build-graalvm-images:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Copy GraalVM Bundle from S3
        run: aws s3 cp "${{ inputs.bundle_s3_uri }}" ./bundle.nib
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CI_READER_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_READER_SECRET_KEY }}
      - name: Create version.txt
        run: echo "${{ inputs.version }}" >> version.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.PUBLIC_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_WRITE_PAT }}

      - name: Extract metadata for Public Docker
        id: meta-public
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PUBLIC_REGISTRY }}/${{ github.repository_owner }}/${{ inputs.project_name }}
          labels: |
            org.opencontainers.image.revision=${{ inputs.version }}
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ inputs.project_name }}
            org.opencontainers.image.title=${{ inputs.project_name }}
            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ inputs.project_name }}
          tags: |
            type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
            type=raw,value=latest,enable=${{ inputs.is_latest }}
            type=raw,value=testing,enable=${{ inputs.is_testing }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-graalvm
          context: .
          platforms: linux/arm64
          push: true
          pull: true
          tags: ${{ steps.meta-public.outputs.tags }}
          labels: ${{ steps.meta-public.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Login to Harbor Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_REGISTRY_USERNAME }}
          password: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}

      - name: Extract metadata for Private Docker
        id: meta-private
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PRIVATE_REGISTRY }}/${{ env.REPOSITORY }}/${{ inputs.project_name }}
          labels: |
            org.opencontainers.image.revision=${{ inputs.version }}
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ inputs.project_name }}
            org.opencontainers.image.title=${{ inputs.project_name }}
            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ inputs.project_name }}
          tags: |
            type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
            type=raw,value=latest,enable=${{ inputs.is_latest }}
            type=raw,value=testing,enable=${{ inputs.is_testing }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-graalvm
          context: .
          platforms: linux/arm64
          push: true
          pull: true
          tags: ${{ steps.meta-private.outputs.tags }}
          labels: ${{ steps.meta-private.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
