name: Build and publish image

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: origin project name
        required: true

env:
  PUBLIC_REGISTRY: ghcr.io
  REPOSITORY: core0
  PROJECT_NAME: ${{ github.event.repository.name }}
  GRAAL_OPTIMISATION: b

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: arch
      - run: uname -a
